version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'frontend_icecream'
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
        #- /app/node_modules
        #- ./:/app
    environment:
      HOST: 0.0.0.0
